#!/usr/bin/env python3
#
# generate-ca-header.py - turn the embedded license CA PEM into C headers.
#
# Emits a DER header (always) and, optionally, a pins header (dev builds
# only). The DER header carries the trust anchor certificates as byte
# arrays; license.c includes it. The pins header carries the SHA-256
# fingerprints of each anchor certificate and of its SubjectPublicKeyInfo;
# license_pins.c includes it only in a dev build, where the embedded CA is
# a randomly generated dev CA whose fingerprints cannot be hand-written.
# Release builds use the hand-written production pins in license_pins.c
# instead, so the fingerprints live in a different translation unit than
# the embedded bytes.
#
# Uses only the Python standard library plus the openssl command line (for
# the SPKI fingerprint), so no build depends on python-cryptography. The
# openssl CLI is only invoked when a pins header is requested.
#
# Usage:
#   generate-ca-header.py --pem FILE --der-out FILE [--pins-out FILE]

import argparse
import base64
import hashlib
import re
import subprocess
import sys
import tempfile


def parse_pem_certs(text):
    """Return a list of DER byte strings, one per PEM certificate."""
    blocks = re.findall(
        r"-----BEGIN CERTIFICATE-----(.*?)-----END CERTIFICATE-----",
        text,
        re.DOTALL,
    )
    if not blocks:
        sys.exit("no PEM certificate found in input")
    ders = []
    for b in blocks:
        b64 = "".join(b.split())
        ders.append(base64.b64decode(b64))
    return ders


def emit_der_header(ders, path):
    lines = []
    lines.append("/*")
    lines.append(" * appscode_root_ca_der.h - generated; do not edit.")
    lines.append(" *")
    lines.append(" * DER bytes of the embedded license trust anchor(s).")
    lines.append(" * Generated by src/backend/license/generate-ca-header.py.")
    lines.append(" */")
    lines.append("#ifndef APPSCODE_ROOT_CA_DER_H")
    lines.append("#define APPSCODE_ROOT_CA_DER_H")
    lines.append("")
    for idx, der in enumerate(ders):
        lines.append("static const unsigned char appscode_ca_der_%d[] = {" % idx)
        row = []
        body = []
        for i, byte in enumerate(der):
            row.append("0x%02x," % byte)
            if len(row) == 12:
                body.append("\t" + " ".join(row))
                row = []
        if row:
            body.append("\t" + " ".join(row))
        lines.extend(body)
        lines.append("};")
        lines.append("")
    lines.append("typedef struct AppsCodeCaDer")
    lines.append("{")
    lines.append("\tconst unsigned char *der;")
    lines.append("\tunsigned int len;")
    lines.append("} AppsCodeCaDer;")
    lines.append("")
    lines.append("static const AppsCodeCaDer appscode_ca_ders[] = {")
    for idx in range(len(ders)):
        lines.append(
            "\t{appscode_ca_der_%d, (unsigned int) sizeof(appscode_ca_der_%d)},"
            % (idx, idx)
        )
    lines.append("};")
    lines.append("")
    lines.append(
        "#define APPSCODE_CA_COUNT "
        "((int) (sizeof(appscode_ca_ders) / sizeof(appscode_ca_ders[0])))"
    )
    lines.append("")
    lines.append("#endif\t\t\t\t\t\t\t/* APPSCODE_ROOT_CA_DER_H */")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


def spki_sha256(der):
    """SHA-256 over the DER SubjectPublicKeyInfo, via the openssl CLI."""
    with tempfile.NamedTemporaryFile(suffix=".der") as tf:
        tf.write(der)
        tf.flush()
        pub = subprocess.run(
            ["openssl", "x509", "-inform", "DER", "-in", tf.name,
             "-pubkey", "-noout"],
            check=True, capture_output=True,
        ).stdout
        spki_der = subprocess.run(
            ["openssl", "pkey", "-pubin", "-outform", "DER"],
            input=pub, check=True, capture_output=True,
        ).stdout
    return hashlib.sha256(spki_der).hexdigest()


def emit_pins_header(ders, path):
    cert_pins = [hashlib.sha256(d).hexdigest() for d in ders]
    spki_pins = [spki_sha256(d) for d in ders]
    lines = []
    lines.append("/*")
    lines.append(" * appscode_root_ca_pins.h - generated; do not edit.")
    lines.append(" *")
    lines.append(" * SHA-256 fingerprints of the embedded trust anchor(s),")
    lines.append(" * for dev builds only. Release builds use the hand-written")
    lines.append(" * production pins in license_pins.c.")
    lines.append(" */")
    lines.append("#ifndef APPSCODE_ROOT_CA_PINS_H")
    lines.append("#define APPSCODE_ROOT_CA_PINS_H")
    lines.append("")
    lines.append("#define APPSCODE_CA_CERT_SHA256_PINS \\")
    lines.append("\t{ \\")
    for p in cert_pins:
        lines.append('\t\t"%s", \\' % p)
    lines.append("\t}")
    lines.append("")
    lines.append("#define APPSCODE_CA_SPKI_SHA256_PINS \\")
    lines.append("\t{ \\")
    for p in spki_pins:
        lines.append('\t\t"%s", \\' % p)
    lines.append("\t}")
    lines.append("")
    lines.append("#define APPSCODE_CA_PIN_COUNT %d" % len(ders))
    lines.append("")
    lines.append("#endif\t\t\t\t\t\t\t/* APPSCODE_ROOT_CA_PINS_H */")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pem", required=True)
    ap.add_argument("--der-out")
    ap.add_argument("--pins-out")
    args = ap.parse_args()

    if not args.der_out and not args.pins_out:
        ap.error("at least one of --der-out or --pins-out is required")

    with open(args.pem) as f:
        ders = parse_pem_certs(f.read())

    if args.der_out:
        emit_der_header(ders, args.der_out)
    if args.pins_out:
        emit_pins_header(ders, args.pins_out)


if __name__ == "__main__":
    main()
