/*-------------------------------------------------------------------------
 *
 * license_test.c
 *	  Standalone unit-test harness for the license verification core.
 *
 * Runs outside the server: it links only license.c, license_pins.c, the
 * generated header, and OpenSSL. It drives appscode_license_verify() over
 * certificate files generated by scripts/make-license.sh and asserts the
 * expected status for each.
 *
 * Usage:
 *   license_test <case> <path-to-license.pem>
 *   license_test dump  <path-to-license.pem>
 *
 * where <case> is one of the LicenseStatus tags (ok, expired, ...). Exit
 * status is 0 when the observed status matches the expected case, 1
 * otherwise. "dump" prints the parsed fields and the status, always
 * exiting 0, for eyeballing.
 *
 *-------------------------------------------------------------------------
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "license.h"

static void
dump(const LicenseInfo *info)
{
	int			i;

	printf("status       = %s\n", appscode_license_status_tag(info->status));
	printf("reason       = %s\n", info->reason);
	printf("serial       = %s\n", info->serial_dec);
	printf("cn           = %s\n", info->cn);
	printf("product_line = %s\n", info->product_line);
	printf("tier         = %s\n", info->tier);
	printf("plan         = %s\n", info->plan);
	printf("features     = ");
	for (i = 0; i < info->num_features; i++)
		printf("%s%s", i ? "," : "", info->features[i]);
	printf("\n");
	printf("not_before   = %s\n", info->not_before);
	printf("not_after    = %s\n", info->not_after);
	printf("days_left    = %ld\n", info->days_remaining);
	printf("leaf_sha256  = %s\n", info->leaf_sha256);
}

int
main(int argc, char **argv)
{
	LicenseInfo info;
	const char *want;
	const char *path;
	const char *got;

	if (argc != 3)
	{
		fprintf(stderr, "usage: %s <case|dump> <license.pem>\n", argv[0]);
		return 2;
	}
	want = argv[1];
	path = argv[2];

	appscode_license_verify(path, &info);
	got = appscode_license_status_tag(info.status);

	if (strcmp(want, "dump") == 0)
	{
		dump(&info);
		return 0;
	}

	if (strcmp(want, got) != 0)
	{
		fprintf(stderr, "FAIL: expected status \"%s\", got \"%s\" (%s)\n",
				want, got, info.reason);
		return 1;
	}
	printf("ok: %s (%s)\n", got, info.reason);
	return 0;
}
